export declare const makeEventChecker: (value: string, split?: string) => string;
export declare const PIPE: (...args: string[]) => string;
export declare const EVENT: (...args: string[]) => string;
export declare const COMMAND: (...args: string[]) => string;
export declare const ON: (...args: string[]) => string;
export declare const NAME_SAPARATOR = ":";
export declare const SAPARATOR = " ";
export declare const CHECKER: (value: string, split?: string) => string;
export declare const AFTER: (value: string, split?: string) => string;
export declare const BEFORE: (value: any, split?: string) => string;
export declare const IF: (value: string, split?: string) => string;
export declare const KEY: (value: string, split?: string) => string;
export declare const ARROW_UP: string;
export declare const ARROW_DOWN: string;
export declare const ARROW_LEFT: string;
export declare const ARROW_RIGHT: string;
export declare const ENTER: string;
export declare const SPACE: string;
export declare const ESCAPE: string;
export declare const BACKSPACE: string;
export declare const DELETE: string;
export declare const EQUAL: string;
export declare const MINUS: string;
export declare const BRACKET_RIGHT: string;
export declare const BRACKET_LEFT: string;
export declare const ALT: string;
export declare const SHIFT: string;
export declare const META: string;
export declare const CONTROL: string;
export declare const MOUSE: string;
export declare const TOUCH: string;
export declare const PEN: string;
export declare const SELF: string;
export declare const LEFT_BUTTON: string;
export declare const RIGHT_BUTTON: string;
export declare const FIT: string;
export declare const PASSIVE: string;
export declare const DOMDIFF: string;
export declare const DEBOUNCE: (t?: number) => string;
export declare const DELAY: (t?: number) => string;
export declare const D1000: string;
export declare const THROTTLE: (t?: number) => string;
export declare const ALL_TRIGGER: string;
export declare const SELF_TRIGGER: string;
export declare const FRAME: string;
export declare const PARAMS: (obj: string) => string;
export declare const CAPTURE: string;
export declare const PREVENT: string;
export declare const STOP: string;
export declare const SUBSCRIBE: (...args: string[]) => string;
export declare const SUBSCRIBE_ALL: (...args: any[]) => string;
export declare const SUBSCRIBE_SELF: (...args: any[]) => string;
export declare const CONFIG: (config: any, ...args: any[]) => string;
export declare const CALLBACK: (...args: string[]) => string;
export declare const RAF: string;
export declare const CUSTOM: (...keys: string[]) => (...args: string[]) => string;
export declare const CLICK: (...args: string[]) => string;
export declare const DOUBLECLICK: (...args: string[]) => string;
export declare const MOUSEDOWN: (...args: string[]) => string;
export declare const MOUSEUP: (...args: string[]) => string;
export declare const MOUSEMOVE: (...args: string[]) => string;
export declare const MOUSEOVER: (...args: string[]) => string;
export declare const MOUSEOUT: (...args: string[]) => string;
export declare const MOUSEENTER: (...args: string[]) => string;
export declare const MOUSELEAVE: (...args: string[]) => string;
export declare const TOUCHSTART: (...args: string[]) => string;
export declare const TOUCHMOVE: (...args: string[]) => string;
export declare const TOUCHEND: (...args: string[]) => string;
export declare const KEYDOWN: (...args: string[]) => string;
export declare const KEYUP: (...args: string[]) => string;
export declare const KEYPRESS: (...args: string[]) => string;
export declare const DRAG: (...args: string[]) => string;
export declare const DRAGSTART: (...args: string[]) => string;
export declare const DROP: (...args: string[]) => string;
export declare const DRAGOVER: (...args: string[]) => string;
export declare const DRAGENTER: (...args: string[]) => string;
export declare const DRAGLEAVE: (...args: string[]) => string;
export declare const DRAGEXIT: (...args: string[]) => string;
export declare const DRAGOUT: (...args: string[]) => string;
export declare const DRAGEND: (...args: string[]) => string;
export declare const CONTEXTMENU: (...args: string[]) => string;
export declare const CHANGE: (...args: string[]) => string;
export declare const INPUT: (...args: string[]) => string;
export declare const FOCUS: (...args: string[]) => string;
export declare const FOCUSIN: (...args: string[]) => string;
export declare const FOCUSOUT: (...args: string[]) => string;
export declare const BLUR: (...args: string[]) => string;
export declare const PASTE: (...args: string[]) => string;
export declare const RESIZE: (...args: string[]) => string;
export declare const SCROLL: (...args: string[]) => string;
export declare const SUBMIT: (...args: string[]) => string;
export declare const POINTERSTART: (...args: any[]) => string;
export declare const POINTEROVER: (...args: string[]) => string;
export declare const POINTERENTER: (...args: string[]) => string;
export declare const POINTEROUT: (...args: string[]) => string;
export declare const POINTERMOVE: (...args: string[]) => string;
export declare const POINTEREND: (...args: string[]) => string;
export declare const CHANGEINPUT: (...args: string[]) => string;
export declare const WHEEL: (...args: string[]) => string;
export declare const ANIMATIONSTART: (...args: string[]) => string;
export declare const ANIMATIONEND: (...args: string[]) => string;
export declare const ANIMATIONITERATION: (...args: string[]) => string;
export declare const TRANSITIONSTART: (...args: string[]) => string;
export declare const TRANSITIONEND: (...args: string[]) => string;
export declare const TRANSITIONRUN: (...args: string[]) => string;
export declare const TRANSITIONCANCEL: (...args: string[]) => string;
export declare const DOUBLETAB: (...args: string[]) => string;
export declare const LOAD: (value?: string) => string;
export declare const getRef: (id: string | number) => any;
export declare const BIND_CHECK_FUNCTION: (field: string | number) => () => boolean;
export declare const BIND_CHECK_DEFAULT_FUNCTION: () => boolean;
export declare const BIND: (value?: string) => string;
export declare function normalizeWheelEvent(e: {
    deltaX: any;
    deltaY: any;
    shiftKey: any;
    deltaMode: number;
}): number[];
declare const _default: {
    addDomEvent(dom: Element, eventName: keyof ElementEventMap, callback: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeDomEvent(dom: Element, eventName: keyof ElementEventMap, callback: EventListenerOrEventListenerObject): void;
    pos(e: {
        touches: any[];
    }): any;
    posXY(e: any): {
        x: any;
        y: any;
    };
};
export default _default;
